### ISSUE TITLE
can you horizontally align the "view toolkit" buttons?

### ISSUE THREAD

**Issue by tvol** [billymeinke/cc-toolkits#2]

**Comment by billymeinke** [comment]
Can you draw or sketch what you have in mind? It's probably doable.

**Comment by tvol** [comment]
I just mean so that the grey boxes line up with with red line. I think
right now the middle one is forcing the box lower because that's how the
text broke--but perhaps it doesn't really matter since the whole thing
sizes dynamically, huh?
[image: Inline image 1]

On Fri, Jan 2, 2015 at 5:04 PM, Billy Meinke notifications@github.com
wrote:

> Can you draw or sketch what you have in mind? It's probably doable.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/billymeinke/cc-toolkits/issues/2#issuecomment-68577390
> .

## 

Timothy Vollmer
Public Policy Manager, Creative Commons
Get Creative Commons Updates http://bit.ly/commonsnews
